export interface ButtonProps { 
    id?: any,
    name?: string,
    required?:boolean,
    className?: any, 
    style?: any, 
    onclick?: any, 
    ondblclick?: any, 
    onmousedown?: any, 
    onmousemove?: any, 
    onmouseout?: any, 
    onmouseover?: any, 
    onmouseup?: any, 
    onkeydown?: any, 
    onkeypress?: any, 
    onkeyup?: any,
    onhover?: any,
    children?: any,
    [key: string]: any
}