export interface TableProps { 
    id?: any,
    border?: string,
    className?: any, 
    dir?: any, 
    lang?: any, 
    style?: any, 
    xmlLang?: any, 
    onclick?: any, 
    ondblclick?: any, 
    onmousedown?: any, 
    onmousemove?: any, 
    onmouseout?: any, 
    onmouseover?: any, 
    onmouseup?: any, 
    onkeydown?: any, 
    onkeypress?: any, 
    onkeyup?: any, 
    children?: any,
    [key: string]: any
}


export interface TableColumnProps { 
    type?: "td" | "th",
    id?: any,
    border?: string,
    className?: any, 
    dir?: any, 
    lang?: any, 
    style?: any, 
    xmlLang?: any, 
    onclick?: any, 
    ondblclick?: any, 
    onmousedown?: any, 
    onmousemove?: any, 
    onmouseout?: any, 
    onmouseover?: any, 
    onmouseup?: any, 
    onkeydown?: any, 
    onkeypress?: any, 
    onkeyup?: any, 
    children?: any,
    [key: string]: any
}
